
const char* const Icons::camera_data[] = {
"27 27 32 1",
". c None",
"x c #000000",
"q c #0e0e0e",
"n c #1a1a1a",
"o c #262626",
"m c #323232",
"l c #3e3e3e",
"h c #4a4a4a",
"A c #503200",
"z c #505000",
"i c #565656",
"g c #626262",
"k c #6e6e6e",
"y c #734a00",
"v c #737300",
"b c #7a7a7a",
"w c #808000",
"j c #808080",
"a c #868686",
"c c #929292",
"t c #969600",
"e c #9e9e9e",
"D c #a0a0a4",
"# c #aaaaaa",
"d c #b6b6b6",
"C c #c0c0c0",
"p c #c2c2c2",
"f c #cecece",
"B c #dadada",
"s c #ffb848",
"r c #ffc66b",
"u c #ffff6b",
"..#abc#......deae..........",
"fghiibjaf..fjigkajcf.......",
"bhiiiibcjf.ghiiiibajf......",
"hiiiiiikja#hiiiiiikbk......",
"liiiiiiikkgiiiiiiiikid.....",
"liiiiiiiikiiiiggiiiigk.....",
"ihiimiiiiihiigmlgiiiim.....",
"bhihnmiiigliigoohiiiin.....",
"plhhimhiiioiiiioiiiiiq.....",
".ahrrsjihhniiiigiiiihl.....",
"..itsrusebvrihiiiiiind.....",
"..fwwttsss#ssihhiiil#......",
"...wxogttess#stimmlvv......",
"...wtgqxmatt#sssstttybe#f..",
"...awttvoxbawa#rrrswzkbkkcp",
"..fcwaattkigawwwtrvzzjbbbkb",
"..#jwwaatkhhhgjaawhzzajjjjb",
"..#cwtaatkhiiihitwzlhaaagmb",
"..#cxztatwhhiihgtwzhhlhmxx#",
"...djlAvvttwihhitwhaahlndhB",
".....#azAqtttwigtvmlilmgdkB",
"......##czxgvttttvnommnCbcf",
".......D#dazootttgAlmoodhkk",
".........D##azAmtzlkcnhchbj",
"..........DD##akwziddkxokbp",
"............###dak###dhijd.",
"................fp...Dpcp.."};

const char** Icons::cameraIcon()
{
  return ((const char**) camera_data);
}

